name: Deploy Dev Menually

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Environment name (e.g., dev, staging)"
        required: true
        default: "dev"
        type: choice
        options: ["dev"]
      api_url:
        description: "API URL for deployment"
        required: true
        default: "https://api.degenmarkets.com"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Linting with ESLint
        run: npm run lint

  manual-deploy:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Remove .vercel directory
        run: rm -rf .vercel

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          API_URL: ${{ github.event.inputs.api_url }}
          HELIUS_URL: ${{ secrets.DEV_HELIUS_URL }}

        run: |
          npm install -g vercel

          # Deploy to Vercel and capture the deployment URL

          DEPLOYMENT_URL=$(vercel --prod --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --yes \
            --env API_URL=$API_URL --env HELIUS_URL=$HELIUS_URL | tee deployment.log | grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app')

          echo "Primary Deployment URL: $DEPLOYMENT_URL"

          # Attempt to assign the alias and capture any errors
          set -o pipefail
          vercel alias set $DEPLOYMENT_URL ${{ github.event.inputs.env_name }}.degenmarkets.com --token $VERCEL_TOKEN || {
            echo "Failed to set alias. Check domain permissions."
            exit 1
          }

          echo "Access your application at: $DEPLOYMENT_URL"
