name: Deploy to Vercel

on:
  workflow_dispatch:
    inputs:
      env_name:
        description: "Environment name (e.g., dev, staging)"
        required: true
        default: "dev"
        type: choice
        options: ["dev", "staging"]
      api_url:
        description: "API URL for deployment"
        required: true
        default: "https://api.qalbehabib.com"
      helius_url:
        description: "Helius URL for deployment"
        required: true

jobs:
  manual-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          API_URL: ${{ github.event.inputs.api_url }}
          HELIUS_URL: ${{ github.event.inputs.helius_url }}
        run: |
          npm install -g vercel

          # Deploy to Vercel and capture the deployment URL
          DEPLOYMENT_URL=$(vercel --prod --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --confirm \
            --env API_URL=$API_URL --env HELIUS_URL=$HELIUS_URL | tee deployment.log | grep -o 'https:\/\/[a-zA-Z0-9.-]*\.vercel\.app')

          echo "Primary Deployment URL: $DEPLOYMENT_URL"

          # Set a custom alias based on the environment name provided in the workflow dispatch input
          vercel alias set $DEPLOYMENT_URL ${{ github.event.inputs.env_name }}.qalbehabib.com --token $VERCEL_TOKEN
